-- QuickEval V1 initial schema
-- Target: MySQL 8.4 LTS
-- UUIDv7 values are generated by the Go application and stored as BINARY(16).

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE users (
    id BINARY(16) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    disabled_at DATETIME(3) NULL,
    disabled_by BINARY(16) NULL,
    created_by BINARY(16) NULL,
    updated_by BINARY(16) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email (email),
    KEY idx_users_status_created (status, created_at),
    KEY idx_users_disabled_by (disabled_by),
    KEY idx_users_created_by (created_by),
    KEY idx_users_updated_by (updated_by),
    CONSTRAINT chk_users_name CHECK (CHAR_LENGTH(TRIM(display_name)) > 0),
    CONSTRAINT chk_users_role CHECK (role IN ('member', 'admin')),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT chk_users_disabled CHECK (
        (status = 'active' AND disabled_at IS NULL AND disabled_by IS NULL)
        OR
        (status = 'disabled' AND disabled_at IS NOT NULL AND disabled_by IS NOT NULL)
    ),
    CONSTRAINT fk_users_disabled_by FOREIGN KEY (disabled_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_identities (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NULL,
    status VARCHAR(20) NOT NULL,
    last_login_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_identities_provider_subject (provider, provider_subject),
    UNIQUE KEY uq_user_identities_user_provider (user_id, provider),
    KEY idx_user_identities_status_updated (status, updated_at),
    CONSTRAINT chk_user_identities_provider CHECK (provider IN ('local', 'oa')),
    CONSTRAINT chk_user_identities_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT chk_user_identities_credentials CHECK (
        (provider = 'local' AND password_hash IS NOT NULL)
        OR
        (provider = 'oa' AND password_hash IS NULL)
    ),
    CONSTRAINT chk_user_identities_subject CHECK (CHAR_LENGTH(TRIM(provider_subject)) > 0),
    CONSTRAINT fk_user_identities_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_targets (
    id BINARY(16) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_targets_name (name),
    KEY idx_evaluation_targets_status_updated (status, updated_at),
    KEY idx_evaluation_targets_created_by (created_by),
    KEY idx_evaluation_targets_updated_by (updated_by),
    CONSTRAINT chk_evaluation_targets_name CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    CONSTRAINT chk_evaluation_targets_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT fk_evaluation_targets_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_evaluation_targets_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE scenarios (
    id BINARY(16) NOT NULL,
    evaluation_target_id BINARY(16) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_scenarios_target_name (evaluation_target_id, name),
    KEY idx_scenarios_target_status_updated (evaluation_target_id, status, updated_at),
    KEY idx_scenarios_created_by (created_by),
    KEY idx_scenarios_updated_by (updated_by),
    CONSTRAINT chk_scenarios_name CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    CONSTRAINT chk_scenarios_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT fk_scenarios_target FOREIGN KEY (evaluation_target_id) REFERENCES evaluation_targets (id) ON DELETE RESTRICT,
    CONSTRAINT fk_scenarios_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_scenarios_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE case_tags (
    id BINARY(16) NOT NULL,
    scenario_id BINARY(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_case_tags_scenario_name (scenario_id, name),
    KEY idx_case_tags_scenario_status_sort (scenario_id, status, sort_order),
    KEY idx_case_tags_created_by (created_by),
    KEY idx_case_tags_updated_by (updated_by),
    CONSTRAINT chk_case_tags_name CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    CONSTRAINT chk_case_tags_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT fk_case_tags_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id) ON DELETE RESTRICT,
    CONSTRAINT fk_case_tags_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_case_tags_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE datasets (
    id BINARY(16) NOT NULL,
    scenario_id BINARY(16) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_datasets_scenario_name (scenario_id, name),
    KEY idx_datasets_scenario_status_updated (scenario_id, status, updated_at),
    KEY idx_datasets_created_by (created_by),
    KEY idx_datasets_updated_by (updated_by),
    CONSTRAINT chk_datasets_name CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    CONSTRAINT chk_datasets_status CHECK (status IN ('active', 'archived')),
    CONSTRAINT fk_datasets_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id) ON DELETE RESTRICT,
    CONSTRAINT fk_datasets_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_datasets_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dataset_versions (
    id BINARY(16) NOT NULL,
    dataset_id BINARY(16) NOT NULL,
    base_version_id BINARY(16) NULL,
    version_no INT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    release_note TEXT NULL,
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    published_at DATETIME(3) NULL,
    published_by BINARY(16) NULL,
    archived_at DATETIME(3) NULL,
    archived_by BINARY(16) NULL,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_dataset_versions_number (dataset_id, version_no),
    KEY idx_dataset_versions_status_created (dataset_id, status, created_at),
    KEY idx_dataset_versions_base (base_version_id),
    KEY idx_dataset_versions_published_by (published_by),
    KEY idx_dataset_versions_archived_by (archived_by),
    KEY idx_dataset_versions_created_by (created_by),
    KEY idx_dataset_versions_updated_by (updated_by),
    CONSTRAINT chk_dataset_versions_status CHECK (status IN ('draft', 'published', 'archived')),
    CONSTRAINT chk_dataset_versions_lifecycle CHECK (
        (
            status = 'draft'
            AND version_no IS NULL
            AND published_at IS NULL
            AND published_by IS NULL
            AND archived_at IS NULL
            AND archived_by IS NULL
        )
        OR
        (
            status = 'published'
            AND version_no IS NOT NULL
            AND version_no > 0
            AND published_at IS NOT NULL
            AND published_by IS NOT NULL
            AND archived_at IS NULL
            AND archived_by IS NULL
        )
        OR
        (
            status = 'archived'
            AND version_no IS NOT NULL
            AND version_no > 0
            AND published_at IS NOT NULL
            AND published_by IS NOT NULL
            AND archived_at IS NOT NULL
            AND archived_by IS NOT NULL
        )
    ),
    CONSTRAINT fk_dataset_versions_dataset FOREIGN KEY (dataset_id) REFERENCES datasets (id) ON DELETE RESTRICT,
    CONSTRAINT fk_dataset_versions_base FOREIGN KEY (base_version_id) REFERENCES dataset_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_dataset_versions_published_by FOREIGN KEY (published_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_dataset_versions_archived_by FOREIGN KEY (archived_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_dataset_versions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_dataset_versions_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE version_cases (
    id BINARY(16) NOT NULL,
    dataset_version_id BINARY(16) NOT NULL,
    case_key BINARY(16) NOT NULL,
    name VARCHAR(200) NULL,
    user_prompt MEDIUMTEXT NOT NULL,
    precondition MEDIUMTEXT NULL,
    expected_result MEDIUMTEXT NULL,
    judging_guide MEDIUMTEXT NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_version_cases_version_key (dataset_version_id, case_key),
    KEY idx_version_cases_enabled_sort (dataset_version_id, is_enabled, sort_order),
    KEY idx_version_cases_key_version (case_key, dataset_version_id),
    KEY idx_version_cases_created_by (created_by),
    KEY idx_version_cases_updated_by (updated_by),
    CONSTRAINT chk_version_cases_prompt CHECK (CHAR_LENGTH(TRIM(user_prompt)) > 0),
    CONSTRAINT chk_version_cases_enabled CHECK (is_enabled IN (FALSE, TRUE)),
    CONSTRAINT fk_version_cases_version FOREIGN KEY (dataset_version_id) REFERENCES dataset_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_version_cases_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_version_cases_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE version_case_tags (
    id BINARY(16) NOT NULL,
    version_case_id BINARY(16) NOT NULL,
    case_tag_id BINARY(16) NOT NULL,
    tag_name_snapshot VARCHAR(100) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_version_case_tags_pair (version_case_id, case_tag_id),
    KEY idx_version_case_tags_tag_case (case_tag_id, version_case_id),
    KEY idx_version_case_tags_created_by (created_by),
    CONSTRAINT chk_version_case_tags_name CHECK (CHAR_LENGTH(TRIM(tag_name_snapshot)) > 0),
    CONSTRAINT fk_version_case_tags_case FOREIGN KEY (version_case_id) REFERENCES version_cases (id) ON DELETE CASCADE,
    CONSTRAINT fk_version_case_tags_tag FOREIGN KEY (case_tag_id) REFERENCES case_tags (id) ON DELETE RESTRICT,
    CONSTRAINT fk_version_case_tags_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_runs (
    id BINARY(16) NOT NULL,
    dataset_version_id BINARY(16) NOT NULL,
    evaluator_id BINARY(16) NOT NULL,
    agent_version VARCHAR(100) NOT NULL,
    environment VARCHAR(20) NOT NULL,
    purpose_note TEXT NULL,
    config_note MEDIUMTEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'in_progress',
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    first_completed_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    voided_at DATETIME(3) NULL,
    voided_by BINARY(16) NULL,
    void_reason TEXT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_evaluation_runs_version_status_time (dataset_version_id, status, completed_at),
    KEY idx_evaluation_runs_evaluator_status_time (evaluator_id, status, completed_at),
    KEY idx_evaluation_runs_status_time (status, completed_at),
    KEY idx_evaluation_runs_environment_status_time (environment, status, completed_at),
    KEY idx_evaluation_runs_agent_status_time (agent_version, status, completed_at),
    KEY idx_evaluation_runs_voided_by (voided_by),
    KEY idx_evaluation_runs_updated_by (updated_by),
    CONSTRAINT chk_evaluation_runs_agent_version CHECK (CHAR_LENGTH(TRIM(agent_version)) > 0),
    CONSTRAINT chk_evaluation_runs_environment CHECK (environment IN ('test', 'staging', 'production', 'other')),
    CONSTRAINT chk_evaluation_runs_status CHECK (status IN ('in_progress', 'completed', 'voided')),
    CONSTRAINT chk_evaluation_runs_lifecycle CHECK (
        (
            status = 'in_progress'
            AND completed_at IS NULL
            AND voided_at IS NULL
            AND voided_by IS NULL
            AND void_reason IS NULL
        )
        OR
        (
            status = 'completed'
            AND first_completed_at IS NOT NULL
            AND completed_at IS NOT NULL
            AND voided_at IS NULL
            AND voided_by IS NULL
            AND void_reason IS NULL
        )
        OR
        (
            status = 'voided'
            AND voided_at IS NOT NULL
            AND voided_by IS NOT NULL
            AND void_reason IS NOT NULL
            AND CHAR_LENGTH(TRIM(void_reason)) > 0
        )
    ),
    CONSTRAINT fk_evaluation_runs_version FOREIGN KEY (dataset_version_id) REFERENCES dataset_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_evaluation_runs_evaluator FOREIGN KEY (evaluator_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_evaluation_runs_voided_by FOREIGN KEY (voided_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_evaluation_runs_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE case_results (
    id BINARY(16) NOT NULL,
    evaluation_run_id BINARY(16) NOT NULL,
    version_case_id BINARY(16) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    answer_text MEDIUMTEXT NULL,
    score TINYINT UNSIGNED NULL,
    comment MEDIUMTEXT NULL,
    skip_reason TEXT NULL,
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_case_results_run_case (evaluation_run_id, version_case_id),
    KEY idx_case_results_run_status_score (evaluation_run_id, status, score),
    KEY idx_case_results_case_status (version_case_id, status),
    KEY idx_case_results_updated_by (updated_by),
    CONSTRAINT chk_case_results_status CHECK (status IN ('pending', 'evaluated', 'skipped')),
    CONSTRAINT chk_case_results_score CHECK (score IS NULL OR score BETWEEN 1 AND 5),
    CONSTRAINT chk_case_results_state CHECK (
        (status = 'pending' AND score IS NULL AND skip_reason IS NULL)
        OR
        (status = 'evaluated' AND skip_reason IS NULL)
        OR
        (
            status = 'skipped'
            AND score IS NULL
            AND skip_reason IS NOT NULL
            AND CHAR_LENGTH(TRIM(skip_reason)) > 0
        )
    ),
    CONSTRAINT fk_case_results_run FOREIGN KEY (evaluation_run_id) REFERENCES evaluation_runs (id) ON DELETE CASCADE,
    CONSTRAINT fk_case_results_case FOREIGN KEY (version_case_id) REFERENCES version_cases (id) ON DELETE RESTRICT,
    CONSTRAINT fk_case_results_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE badcases (
    id BINARY(16) NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    scenario_id BINARY(16) NOT NULL,
    case_result_id BINARY(16) NULL,
    title VARCHAR(200) NOT NULL,
    description MEDIUMTEXT NULL,
    agent_response_text MEDIUMTEXT NULL,
    agent_version VARCHAR(100) NULL,
    environment VARCHAR(20) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    business_reference VARCHAR(200) NULL,
    session_id VARCHAR(200) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    assignee_id BINARY(16) NULL,
    resolved_at DATETIME(3) NULL,
    invalidated_at DATETIME(3) NULL,
    invalidated_by BINARY(16) NULL,
    invalid_reason TEXT NULL,
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_badcases_case_result (case_result_id),
    KEY idx_badcases_scenario_valid_status_time (scenario_id, invalidated_at, status, occurred_at),
    KEY idx_badcases_assignee_valid_status_updated (assignee_id, invalidated_at, status, updated_at),
    KEY idx_badcases_source_valid_time (source_type, invalidated_at, occurred_at),
    KEY idx_badcases_environment_valid_time (environment, invalidated_at, occurred_at),
    KEY idx_badcases_agent_valid_time (agent_version, invalidated_at, occurred_at),
    KEY idx_badcases_scenario_business_ref (scenario_id, business_reference),
    KEY idx_badcases_scenario_session (scenario_id, session_id),
    KEY idx_badcases_invalidated_by (invalidated_by),
    KEY idx_badcases_created_by (created_by),
    KEY idx_badcases_updated_by (updated_by),
    CONSTRAINT chk_badcases_source CHECK (source_type IN ('evaluation', 'business')),
    CONSTRAINT chk_badcases_title CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT chk_badcases_environment CHECK (environment IN ('test', 'staging', 'production', 'other')),
    CONSTRAINT chk_badcases_status CHECK (status IN ('pending', 'processing', 'resolved', 'deferred')),
    CONSTRAINT chk_badcases_source_result CHECK (
        (source_type = 'evaluation' AND case_result_id IS NOT NULL)
        OR
        (
            source_type = 'business'
            AND case_result_id IS NULL
            AND description IS NOT NULL
            AND CHAR_LENGTH(TRIM(description)) > 0
        )
    ),
    CONSTRAINT chk_badcases_resolved CHECK (
        (status = 'resolved' AND resolved_at IS NOT NULL)
        OR
        (status <> 'resolved' AND resolved_at IS NULL)
    ),
    CONSTRAINT chk_badcases_invalidated CHECK (
        (invalidated_at IS NULL AND invalidated_by IS NULL AND invalid_reason IS NULL)
        OR
        (
            invalidated_at IS NOT NULL
            AND invalidated_by IS NOT NULL
            AND invalid_reason IS NOT NULL
            AND CHAR_LENGTH(TRIM(invalid_reason)) > 0
        )
    ),
    CONSTRAINT fk_badcases_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcases_case_result FOREIGN KEY (case_result_id) REFERENCES case_results (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcases_assignee FOREIGN KEY (assignee_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcases_invalidated_by FOREIGN KEY (invalidated_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcases_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcases_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE issue_tags (
    id BINARY(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    lock_version INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_issue_tags_name (name),
    KEY idx_issue_tags_status_sort (status, sort_order),
    KEY idx_issue_tags_created_by (created_by),
    KEY idx_issue_tags_updated_by (updated_by),
    CONSTRAINT chk_issue_tags_name CHECK (CHAR_LENGTH(TRIM(name)) > 0),
    CONSTRAINT chk_issue_tags_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT fk_issue_tags_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_issue_tags_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE badcase_issue_tags (
    id BINARY(16) NOT NULL,
    badcase_id BINARY(16) NOT NULL,
    issue_tag_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_badcase_issue_tags_pair (badcase_id, issue_tag_id),
    KEY idx_badcase_issue_tags_tag_case (issue_tag_id, badcase_id),
    KEY idx_badcase_issue_tags_created_by (created_by),
    CONSTRAINT fk_badcase_issue_tags_badcase FOREIGN KEY (badcase_id) REFERENCES badcases (id) ON DELETE CASCADE,
    CONSTRAINT fk_badcase_issue_tags_tag FOREIGN KEY (issue_tag_id) REFERENCES issue_tags (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcase_issue_tags_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE badcase_activities (
    id BINARY(16) NOT NULL,
    badcase_id BINARY(16) NOT NULL,
    activity_type VARCHAR(30) NOT NULL,
    from_status VARCHAR(20) NULL,
    to_status VARCHAR(20) NULL,
    from_assignee_id BINARY(16) NULL,
    to_assignee_id BINARY(16) NULL,
    note MEDIUMTEXT NULL,
    actor_id BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_badcase_activities_case_time (badcase_id, created_at, id),
    KEY idx_badcase_activities_actor_time (actor_id, created_at),
    KEY idx_badcase_activities_from_assignee (from_assignee_id),
    KEY idx_badcase_activities_to_assignee (to_assignee_id),
    CONSTRAINT chk_badcase_activities_type CHECK (
        activity_type IN ('created', 'status_changed', 'assignee_changed', 'note_added', 'invalidated', 'reactivated')
    ),
    CONSTRAINT chk_badcase_activities_status_values CHECK (
        (from_status IS NULL OR from_status IN ('pending', 'processing', 'resolved', 'deferred'))
        AND
        (to_status IS NULL OR to_status IN ('pending', 'processing', 'resolved', 'deferred'))
    ),
    CONSTRAINT chk_badcase_activities_shape CHECK (
        (
            activity_type = 'status_changed'
            AND from_status IS NOT NULL
            AND to_status IS NOT NULL
            AND from_status <> to_status
        )
        OR
        (
            activity_type = 'assignee_changed'
            AND (
                (from_assignee_id IS NULL AND to_assignee_id IS NOT NULL)
                OR
                (from_assignee_id IS NOT NULL AND to_assignee_id IS NULL)
                OR
                (from_assignee_id IS NOT NULL AND to_assignee_id IS NOT NULL AND from_assignee_id <> to_assignee_id)
            )
        )
        OR
        (
            activity_type IN ('note_added', 'invalidated', 'reactivated')
            AND note IS NOT NULL
            AND CHAR_LENGTH(TRIM(note)) > 0
        )
        OR
        activity_type = 'created'
    ),
    CONSTRAINT fk_badcase_activities_badcase FOREIGN KEY (badcase_id) REFERENCES badcases (id) ON DELETE CASCADE,
    CONSTRAINT fk_badcase_activities_from_assignee FOREIGN KEY (from_assignee_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcase_activities_to_assignee FOREIGN KEY (to_assignee_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_badcase_activities_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE attachments (
    id BINARY(16) NOT NULL,
    case_result_id BINARY(16) NULL,
    badcase_id BINARY(16) NULL,
    storage_path VARCHAR(500) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    media_type VARCHAR(100) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    sha256 BINARY(32) NOT NULL,
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_by BINARY(16) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_attachments_storage_path (storage_path),
    KEY idx_attachments_result_sort (case_result_id, sort_order),
    KEY idx_attachments_badcase_sort (badcase_id, sort_order),
    KEY idx_attachments_sha256 (sha256),
    KEY idx_attachments_created_by (created_by),
    CONSTRAINT chk_attachments_owner CHECK (
        (case_result_id IS NOT NULL AND badcase_id IS NULL)
        OR
        (case_result_id IS NULL AND badcase_id IS NOT NULL)
    ),
    CONSTRAINT chk_attachments_name CHECK (
        CHAR_LENGTH(TRIM(storage_path)) > 0
        AND CHAR_LENGTH(TRIM(original_name)) > 0
    ),
    CONSTRAINT chk_attachments_media CHECK (media_type IN ('image/png', 'image/jpeg', 'image/webp')),
    CONSTRAINT chk_attachments_size CHECK (file_size > 0 AND file_size <= 10485760),
    CONSTRAINT chk_attachments_dimensions CHECK (
        (width IS NULL AND height IS NULL)
        OR
        (width IS NOT NULL AND width > 0 AND height IS NOT NULL AND height > 0)
    ),
    CONSTRAINT fk_attachments_result FOREIGN KEY (case_result_id) REFERENCES case_results (id) ON DELETE CASCADE,
    CONSTRAINT fk_attachments_badcase FOREIGN KEY (badcase_id) REFERENCES badcases (id) ON DELETE CASCADE,
    CONSTRAINT fk_attachments_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_logs (
    id BINARY(16) NOT NULL,
    actor_user_id BINARY(16) NULL,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BINARY(16) NOT NULL,
    before_data JSON NULL,
    after_data JSON NULL,
    request_id VARCHAR(64) NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(512) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_audit_logs_entity_time (entity_type, entity_id, created_at),
    KEY idx_audit_logs_actor_time (actor_user_id, created_at),
    KEY idx_audit_logs_request (request_id),
    KEY idx_audit_logs_created (created_at),
    CONSTRAINT chk_audit_logs_action CHECK (CHAR_LENGTH(TRIM(action)) > 0),
    CONSTRAINT chk_audit_logs_entity_type CHECK (CHAR_LENGTH(TRIM(entity_type)) > 0),
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
